### ISSUE TITLE
Train_TransE中bfgs()有点问题

### ISSUE THREAD

**Issue by chenbjin** [thunlp/KB2E#10]
bfgs()中保存实体和关系词向量的代码应该在epoch循环之外吧？

目前这样重复写，并没有保存中间结果，反而延长了训练时间

**Comment by Mrlyk423** [comment]
那个是用于训练中间可以随时检测中间结果的，如不需要，可以移到外面。

**Comment by chenbjin** [comment]
@Mrlyk423 明白了，谢谢！我在此基础上扩展了一下。
