### ISSUE TITLE
论文中说训练3分钟，为什么我的得跑好几个小时。

### ISSUE THREAD

**Issue by lylalala** [thunlp/KB2E#14]
大神们是在服务器上跑的？我训练的wn18，跑了6个小时。求解，祝好。

**Comment by hfsugar** [comment]
我也是要跑好几天。。有没有方法解决？

**Comment by hfsugar** [comment]
I have solved by multi-threads.  @lylalala

**Comment by kimiqq** [comment]
can you share your code @hfsugar

**Comment by hfsugar** [comment]
就是官方出来的代码，不过多线程跑就行了


在2017年06月05日 16:00，kimiqq 写道:

can you share your code @hfsugar

**Comment by kimiqq** [comment]
能留个邮箱么，有些问题请教 @hfsugar

**Comment by zhangyi85** [comment]
没有进行优化吧

**Comment by Mrlyk423** [comment]
这是论文代码，没有进行优化，优化版见我们组github下FastTransX。

**Comment by HongxuChenUQ** [comment]
@kimiqq 你好，请问一下多线程实现了吗？  能不能分享下 怎么写的？

**Comment by kimiqq** [comment]
https://github.com/thunlp/Fast-TransX

发送自 Windows 10 版邮件应用

发件人: HongxuChenUQ
发送时间: 2017年12月3日 7:56
收件人: thunlp/KB2E
抄送: kimiqq; Mention
主题: Re: [thunlp/KB2E] 论文中说训练3分钟，为什么我的得跑好几个小时。 (#14)

@kimiqq 你好，请问一下多线程实现了吗？ 能不能分享下 怎么写的？
