### ISSUE TITLE
How to generate e1_e2.txt

### ISSUE THREAD

**Issue by kimiqq** [thunlp/KB2E#18]
you mean e1_e2.txt as all top-500 entity pairs mentioned in the task entity prediction.
Can you explain how to generate e1_e2.txt explicitly? And what dou you mean all top-500 entity pairs

**Comment by laxatives** [comment]
Documentation on `n2n.txt` would also be appreciated.

**Comment by yanzhangnlp** [comment]
The same question, how to generate e1_e2.txt and n2n.txt? And I found that using n2n.txt cannot generate the same results in PTransE paper. The difference is a little large.

**Comment by Mrlyk423** [comment]
You can download e1_e2.txt at https://pan.baidu.com/s/1i5Mjibb.
