### ISSUE TITLE
关于transH中法向量的更新

### ISSUE THREAD

**Issue by dtjayaaa12345** [thunlp/KB2E#2]
尊敬的林先生：

关于法向量的更新有2个问题想要请教您：
1）train_transH的法向量Wr为什么要进行如下的更新？(line 292---296)

for (int ii=0; ii<n; ii++)
        {
            A_tmp[rel][ii]+=belta_rate_sum_x_entity_vec[e1][ii];
            A_tmp[rel][ii]-=belta_rate_sum_x_entity_vec[e2][ii];
        }
2）在您编写的代码中是如何保证Wr和r正交的？

谢谢~

**Comment by Mrlyk423** [comment]
2）TransH文章中使得W_r与r正交的方法为优化目标：
W_r*r/||r||^2_2<=epsilon
1）上述式子有两种优化方式：a.优化W b.同时优化W和r，实验结果显示两种优化方式最终效果接近，代码采用优化方式a

**Comment by dtjayaaa12345** [comment]
感谢您的回复~
[https://github.com/thunlp/KG2E/blob/master/TransH/Train_TransH.cpp#L270](url) 
[https://github.com/thunlp/KG2E/blob/master/TransH/Train_TransH.cpp#L294](url)
[https://github.com/thunlp/KG2E/blob/master/TransH/Train_TransH.cpp#L295](url)
能否请您解释一下sum_x 变量的作用和对Wr的更新为什么会涉及到头尾实体向量呢？

谢谢！

**Comment by dtjayaaa12345** [comment]
感谢您的回复~
https://github.com/thunlp/KG2E/blob/master/TransH/Train_TransH.cpp#L270
https://github.com/thunlp/KG2E/blob/master/TransH/Train_TransH.cpp#L294
https://github.com/thunlp/KG2E/blob/master/TransH/Train_TransH.cpp#L295

能否请您解释一下代码中sum_x变量的作用以及Wr的更新为什么会涉及到头尾实体向量呢？

谢谢！

**Comment by Mrlyk423** [comment]
（1）优化目标中有hW_rh^T项，进行梯度计算就会涉及到头尾实体向量
（2)  sum_x应该是对其中实体变量的梯度的累加
