### ISSUE TITLE
Normalize `relation_tmp[rel_neg]` in PTransE/Train_TransE_path.cpp

### ISSUE THREAD

**Issue by laxatives** [thunlp/KB2E#21]
Is there a reason why the section

```
			norm(relation_tmp[rel]);
            		norm(entity_tmp[e1]);
            		norm(entity_tmp[e2]);
            		norm(entity_tmp[j]);
```

Skips normalization of `rel_neg`? This leads to huge scores in `train_kb` for the corrupt relation triple (comparing values like `0.1 + MARGIN > 250` and may lead to fewer gradient updates than expected for each label pair, possibly leading to underfitting.

**Comment by Mrlyk423** [comment]
It's a bug, just fix it.
