### ISSUE TITLE
求教，TransH和TransR的梯度以及L1、L2距离的问题

### ISSUE THREAD

**Issue by zhangyi85** [thunlp/KB2E#22]
1 关于L1和L2的选取问题
Trans系列算法中，对距离的选取对最后的结果有影响么？看了您github上分享的代码，感觉主要是侧重于用L1距离。

2 梯度下降算法中的偏导数取值的问题
参考了您github上的代码，transE的梯度求取没有问题，但是transH和transR算法的梯度求解值，我不是太明白。
具体的细节，我给您发邮件了。
非常感谢!

**Comment by majingbit** [comment]
同问，TransH的梯度公式能给个推导过程吗

**Comment by Mrlyk423** [comment]
1. 我尝试的效果是L1距离在Freebase的数据集上效果比L2距离好不少
2. transH和transR就是简单用链式法则求导即可。
