### ISSUE TITLE
求教，关于testTransE的问题

### ISSUE THREAD

**Issue by zhangyi85** [thunlp/KB2E#23]
请问，最后的输出结果
cout<<"left:"<<lsum/fb_l.size()<<'\t'<<lp_n/fb_l.size()<<"\t"<<lsum_filter/fb_l.size()<<'\t'<<lp_n_filter/fb_l.size()<<endl;
		cout<<"right:"<<rsum/fb_r.size()<<'\t'<<rp_n/fb_r.size()<<'\t'<<rsum_filter/fb_r.size()<<'\t'<<rp_n_filter/fb_r.size()<<endl;
怎么理解？
如何得到论文中链接预测，关系分类，元组分类以及最后的文本关系抽取的结果。
请您给出详细步骤，非常感谢！

**Comment by Xls1994** [comment]
你好，在测试testTranE的时候，出现1345 14951之后提示段错误（核心已转储）是什么原因呢？
现在堆栈的大小已经调到100000了

**Comment by zhangyi85** [comment]
你看一下core，不好意思，我用的是windows跑的

**Comment by Mrlyk423** [comment]
1. 最后输出结果对应链接预测头实体hits(raw), hits(filter), mean rank(raw), mean rank(filter)，以及尾实体hits(raw), hits(filter), mean rank(raw), mean rank(filter)。
2. 元组分类请使用代码分别在FB13和WN11上训练，后用得到的h+r-t训练二分类器
3. 关系抽取请参考NRE和MNRE项目。
