### ISSUE TITLE
difference between results of transE(paper) and transE(our)

### ISSUE THREAD

**Issue by wanpifeng4ever** [thunlp/KB2E#24]
Hi, could anyone please explain what causes the difference between transE(paper) and transE(our) in the evaluation results? Why transE(our) outperforms transE(paper) on hit@10 of FB15K that much?

**Comment by zhangyi85** [comment]
第一，两人的代码不同，结果肯定有差异
第二，根据林博士在paperweekly上的视频，原作者可能在实验上没有优化参数（包括维度，间隔等）

**Comment by wanpifeng4ever** [comment]
zhangyi你好！很感谢你的答疑！想顺便请教多一个问题，就是你有没有做过transR的实验。在超参跟论文一样的情况下，我发现transR很难达到论文所讲的效果，甚至远远没有transE和transH好，提高向量维数也没有用，不知道是不是我的实现哪里出了问题。我有尝试过像论文所说，限制实体向量h的2范数，以及实体向量h经关系的投影矩阵M变换后的向量（hM）的2范数小于1，或者只限制其中一种，或者都不限制，但实验效果都极差，但我看thunlp关于翻译模型的tensorflow实现是根本不对实体向量做范数上的限制。很期待你的回复，谢谢！
            在2017年07月10日 08:46，zhangyi 写道： 第一，两人的代码不同，结果肯定有差异
第二，根据林博士在paperweekly上的视频，原作者可能在实验上没有优化参数（包括维度，间隔等）

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/thunlp/KB2E","title":"thunlp/KB2E","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/thunlp/KB2E"}},"updates":{"snippets":[{"icon":"PERSON","message":"@zhangyi85 in #24: 第一，两人的代码不同，结果肯定有差异\r\n第二，根据林博士在paperweekly上的视频，原作者可能在实验上没有优化参数（包括维度，间隔等）"}],"action":{"name":"View Issue","url":"https://github.com/thunlp/KB2E/issues/24#issuecomment-313976874"}}}

**Comment by wanpifeng4ever** [comment]
谢谢指教！可否再请教一下，貌似transR没有论文说的表现那么好？我的实验中，transR的表现比transE和transH都要差很多，不知道是否是我的代码有问题还是transR的训练难收敛？

**Comment by Mrlyk423** [comment]
TransR需要使用TransE进行初始化，否则收敛不太好。
