### ISSUE TITLE
TransH Wr向量梯度公式的推导过程

### ISSUE THREAD

**Issue by majingbit** [thunlp/KB2E#29]
能给下 TransH 中 Wr 向量的梯度推导过程吗，推不出代码里的结果：
`A_tmp[rel][ii]+=belta*rate*x*tmp1;`
`A_tmp[rel][ii]-=belta*rate*x*tmp2;`
`A_tmp[rel][ii]+=belta*rate*sum_x*entity_vec[e1][ii];`
`A_tmp[rel][ii]-=belta*rate*sum_x*entity_vec[e2][ii];`
谢谢！

**Comment by 27232xsl** [comment]
你好，请问你明白了吗？我也实在看不懂这个地方
