### ISSUE TITLE
entity2id & relation2id mappings 

### ISSUE THREAD

**Issue by mttk** [thunlp/KB2E#3]
I couldn't find a description of the FB15k dataset so I'm asking this question here.

In the dataset, I saw triples such as:
"/m/08mbj32 /m/0d193h   /common/annotation_category/annotations./common/webpage/topic"
(FB15k valid, line 830) 

The relation seems to be 2 joined relations( /common/annotation_category/annotations & /common/webpage/topic) merged into one. Is this how 1-N-1 relations are handled? I found both parts of this specific relation in the relation2id description, but there are some other "concatenated" relations for which I can't find sub-parts.

If you could clear this up, I'd be really grateful.

Best,
Martin

**Comment by Mrlyk423** [comment]
"/common/annotation_category/annotations./common/webpage/topic" is a join relation for the cvt in Freebase.

**Comment by guotong1988** [comment]
@Mrlyk423 What is cvt? Thank you.
