### ISSUE TITLE
关于Trans系列模型训练集的问题

### ISSUE THREAD

**Issue by suoluotree** [thunlp/KB2E#34]
你好，我抽取了FB15K/train.txt中的一个实体/m/04ztj及其所有的关系，发现关系为/people/marriage_union_type/unions_of_this_type./people/marriage/spouse（配偶）有几千条之多，关系为/people/marriage_union_type/unions_of_this_type./people/marriage/location_of_ceremony的也有几百条之多，这明显不可能，为什么训练集中的错误关系会如此之多呢？

**Comment by Mrlyk423** [comment]
你好，这是Freebase里面cvt的一项，对应的是婚姻类型，所以会出现这种一对超多的情况。/m/04ztj实体在Freebase中对应Marriage

**Comment by suoluotree** [comment]
多谢回答，十分感谢
