### ISSUE TITLE
TransR and TransH cannot work

### ISSUE THREAD

**Issue by yanzhangnlp** [thunlp/KB2E#35]
Hi, TransE can work with respect to FB15K, but when TransR and TransH cannot. The error is showed as:
`Segmentation fault: 11`

**Comment by Mrlyk423** [comment]
Please check if the data path is correct in the function "prepare". And for TransR, you need to check if there exists pre-trained TransE model (used in Train_TransR.cpp line 119 to 134).
![image](https://user-images.githubusercontent.com/4026690/32759209-2fba505e-c923-11e7-94fc-51db418ece29.png)

**Comment by yanzhangnlp** [comment]
Thanks, Dr. Lin. It works.
