### ISSUE TITLE
What does the file "n2n.txt" mean?

### ISSUE THREAD

**Issue by YuanKQ** [thunlp/KB2E#36]
如题. 
n2n.txt并没有找到相关的文档说明? 请问n2n.txt是什么文件? 如何计算得到呢?
期待你的回复, 感谢.

**Comment by YuanKQ** [comment]
经过阅读源码, 发现, n2n.txt是区分relation类型的（n-to-n, n-to-1, 1-to-n).
详见Test_train_path.cpp

**Comment by XiaoHongbo-Hope** [comment]
没有很懂两列数据分别的含义
