### ISSUE TITLE
FB15K WN18数据集无法下载

### ISSUE THREAD

**Issue by lllchenlll** [thunlp/KB2E#37]
你好，不知是由于墙的问题还是链接失效，Bordes在NIPS论文里使用的FB15K和WN18数据集下载不了，不知能否分享一下，万分感谢。
邮箱：597768493@qq.com

**Comment by Mrlyk423** [comment]
见 https://pan.baidu.com/s/1jHMAutK 及 https://pan.baidu.com/s/1eSo2PMi

**Comment by lllchenlll** [comment]
感谢回复
