### ISSUE TITLE
transE.py 运行失败

### ISSUE THREAD

**Issue by hashc** [thunlp/KB2E#40]
按照教程运行transE.py出现如下问题
![image](https://user-images.githubusercontent.com/17844045/33605121-55d1f086-d9f3-11e7-92e6-256c08cab18c.png)
源代码并没有做任何改动

**Comment by Mrlyk423** [comment]
这个repo没有python代码啊？

**Comment by hashc** [comment]
您好，已经解决了谢谢，是python3的问题
