### ISSUE TITLE
e1_e2.txt

### ISSUE THREAD

**Issue by hauntedvalleyaspect** [thunlp/KB2E#46]
请问e1_e2.txt文件是如何生成的，作用是什么。

**Comment by Mrxianche** [comment]
同问

**Comment by ShellingFord221** [comment]
同问。如果是top 500 entity pairs in entity prediction的话，对每个entity的预测都不止500个

**Comment by Mrlyk423** [comment]
作用是通过TransE的score为每一个(e1, r, ?)或者(?, r, e2)的 pair 选择出top-500的candidate entity.

**Comment by ShellingFord221** [comment]
但是从文件内容来看，好像并不只是被当做头预测的500个和被当做尾预测的500个加起来共1000个？比如在e1_e2.txt文件中，前1048行都是预测id为0的这个实体？

**Comment by ShellingFord221** [comment]
也就是说文件每一行由空格分割的两个数字分别表示什么呢？非常感谢！

**Comment by hauntedvalleyaspect** [comment]
相关代码是什么

**Comment by ShellingFord221** [comment]
同问，如果能share一下得到e1_e2.txt文件的代码就更好了

**Comment by Mrlyk423** [comment]
e1_e2.txt文件存储的是所有test文件中通过TransE的score预处理出来的entity pair，为了节省空间我们将不同triple的entity pair进行了合并。具体代码在KB2E/PTransE/PTransE_add/Test_TransE_path.cpp:
line258-259,302-303,360-361,445-447.

**Comment by XiaoHongbo-Hope** [comment]
你好，按着论文中描述来说这个文件是包含测试集对应的e1_e2对就可以了吗，还是必须包含所有实体的

**Comment by Mrlyk423** [comment]
需要包含测试集中通过TransE处理出来的top500的entity pair.

**Comment by DR73** [comment]
您好，根据您所说的，我理解的是通过Test_TransE_path.cpp生成e1_e2.txt文件，可是执行PCRA.py时就需要读入e1_e2.txt文件，所以请问e1_e2.txt文件到底是什么时候生成的呢？（代码执行顺序应该是PCRA.py->Train_TransE_path.cpp->Test_TransE_path.cpp吧？）
