### ISSUE TITLE
Train_TransE.cpp在训练过程中存在内存泄漏的问题

### ISSUE THREAD

**Issue by cdzhan** [thunlp/KB2E#5]
您好，
        在调用函数bfgs()训练时内存不断增长，感觉应该是发生了内存泄漏，可是没有找到原因。因为我用的freebase知识库比较大，所以内存占用很严重。您有什么建议吗？

**Comment by Mrlyk423** [comment]
你好，TransE训练中以下句子可能会在训练过程中使得内存增长：
while (ok[make_pair(j,fb_r[i])].count(fb_l[i])>0)
    j=rand_max(entity_num);
该句子用于判断产生的负例是否和已有正例冲突，可以改为：
if (ok.count(make_pair(j,fb_r[i]))>0)
       while (ok[make_pair(j,fb_r[i])].count(fb_l[i])>0)
        j=rand_max(entity_num);

**Comment by cdzhan** [comment]
嗯，问题解决了，谢谢你。另外，我觉得在while循环体内再加入一条判断语句
while (ok[make_pair(j,fb_r[i])].count(fb_l[i])>0)
｛
      j=rand_max(entity_num);
     if (ok.count(make_pair(j,fb_r[i]))==0)
        break;
｝
是不是更好？

**Comment by Mrlyk423** [comment]
对的。

**Comment by guotong1988** [comment]
代码里的fb是freebase的意思吧？

**Comment by zhangyi85** [comment]
我在windows环境下遇到过，查了半天没查出问题，在prepare过程中，有file f1，file f2open后，没有close，添加了两条close语句后，貌似内存泄漏的问题没出现了。
