### ISSUE TITLE
PTransE PCRA algorithm data files

### ISSUE THREAD

**Issue by darvid7** [thunlp/KB2E#52]
Hi! Thanks for making this open source!
I was wondering if the data files (`data/e1_e2.txt"` etc) in https://github.com/thunlp/KB2E/blob/master/PTransE/PCRA.py are avaliable?
Thanks!

**Comment by birantaltinel** [comment]
Hello,
The link to the file is in the readme document line 57; I also paste it here so you can directly download.
https://pan.baidu.com/s/1c2iLtmg

**Comment by darvid7** [comment]
Oh thank you! I must have skipped over that.
