### ISSUE TITLE
MemoryError when running PCRA.py in PTransE

### ISSUE THREAD

**Issue by birantaltinel** [thunlp/KB2E#53]
Hello,
I tried to run the PCRA.py code both in Linux and Windows, but got the following error:
`
Traceback (most recent call last):
  File "PCRA2.py", line 68, in <module>
    ok[seg[1] + " " + seg[0]] = {}
MemoryError
`

I guess it's because the dictionary becomes too large to fit in the memory and results in an error. I have 8 GB of ram on the computer that I tried to run the code.

Any suggestions or fixes for this?

Thanks!!

**Comment by Mrlyk423** [comment]
My computer has 256GB of ram, and maybe you can use a computer with a larger ram.
