### ISSUE TITLE
Can not download E1_e2.txt file

### ISSUE THREAD

**Issue by srravula1** [thunlp/KB2E#54]
Hi,
Appreciate your work.
When I try to download the E1_e2.txt, I am repeatedly getting the below error. Is there any other way to access this file?
Error:A new version of the client has been installed and still cannot be downloaded for reasons

![image](https://user-images.githubusercontent.com/9023352/44537819-b9c4f780-a6cd-11e8-97b6-834666e3caae.png)

**Comment by Mrlyk423** [comment]
You can download here: https://thunlp.oss-cn-qingdao.aliyuncs.com/e1_e2.txt
