### ISSUE TITLE
transE seems doesn't work on DBpedia?

### ISSUE THREAD

**Issue by ShellingFord221** [thunlp/KB2E#59]
Hi guys, do you work transE on DBpedia? I can't get head+relation=tail. Why is that?

**Comment by ShellingFord221** [comment]
Sorry, I mean pTransE. If there is only one path from head to tail, and there is only relation in the path, can we still get head+relation=tail using embeddings trained from pTransE?

**Comment by Mrlyk423** [comment]
Sorry, I do not understand what you mean. Do you mean when given a head entity and a path, how to obtain the tail? In this case, you can calculate the path embedding, and also obtain tail entity similar to TransE by vec(head)+vec(path).

**Comment by kavinduchamiran** [comment]
@ShellingFord221 from where did you obtain DBPedia dataset?
