### ISSUE TITLE
test for pTransE

### ISSUE THREAD

**Issue by ShellingFord221** [thunlp/KB2E#60]
I want to predict head by pTransE according to relation and tail, I should:
1. Use transE to get top 500 candidate entities according to relation and tail
2. Train embeddings of all entities and all relations by Train_TransE_path.cpp
3. Make triple by candidate-relation-tail (500 in total) and put them into PCRA.py to get path.txt, confidence.txt, test_pra.txt for test (I can't form e1_e2.txt and use it because there is no relation mentioned in it.)
4. Use embeddings, path.txt, confidence.txt and test_pra.txt for test by Test_TransE_path.cpp to get pTransE scores and rerank candidates.
Am I correct?

**Comment by Mrlyk423** [comment]
Yes, you are correct.
