### ISSUE TITLE
bad_alloc is called when training pTransE

### ISSUE THREAD

**Issue by ShellingFord221** [thunlp/KB2E#64]
Hi, when I use Train_TransE_path.cpp to train pTransE, there is an error:
      terminate called after throwing an instance of 'std::bad_alloc'
      what():  std::bad_alloc
My server is 96GB RAM, and data is all less than 30MB. 
Why is that??

**Comment by Mrlyk423** [comment]
Is there any output for the program?  One thing you can try is to replace code in Train_TransE_path.cpp as follows:
`line 174:  while (ok[make_pair(e1,rel)].count(j)>0) -->while (ok.count(make_pair(e1,rel))>0 
 && ok[make_pair(e1,rel)].count(j)>0)

line 181: while (ok[make_pair(j,rel)].count(e2)>0) --> while (ok.count(make_pair(j,rel))>0&&ok[make_pair(j,rel)].count(e2)>0)

line 189: while (ok[make_pair(e1,rel_neg)].count(e2)>0) --> while (ok.count(make_pair(e1,rel_neg))>0 && ok[make_pair(e1,rel_neg)].count(e2)>0)

line 196: while (ok[make_pair(e1,rel_neg)].count(e2)>0) --> while (ok.count(make_pair(e1,rel_neg))>0&&ok[make_pair(e1,rel_neg)].count(e2)>0)
`
The original code here will put all the negative instances into the memory and may cost a large memory.
