### ISSUE TITLE
what does test_pra.txt mean in PCRA.py?

### ISSUE THREAD

**Issue by ShellingFord221** [thunlp/KB2E#66]
Hi, when I test pTransE for entity prediction, I have to make test_pra.txt by PCRA.py. But if there are multiple queries (e.g. ?-birthdate-0915, ?-birthplace-US, etc.), should there be multiple test_pra.txt? Or just one document? I'm a little bit confused.

**Comment by Mrlyk423** [comment]
We put the relational paths of all entities in test_pra.txt. For the format of test_pra.txt, you can refer to #63 .
