### ISSUE TITLE
训练数据疑问

### ISSUE THREAD

**Issue by liutianling** [thunlp/KB2E#68]
FB15K 数据集的训练集的一条数据如下：
m/07pd_j       /m/02l7c8       /film/film/genre
/m/017dcd       /m/06v8s0       /tv/tv_program/regular_cast./tv/regular_tv_appearance/actor
请教下这是什么意思，如果前面两个是实体，最后一个是什么意思？最后一个数据每个　/ 　后面分别代表什么意思？
WN18 数据集的形式感觉很明确
3964744        04371774        _hyponym
是不是就是头实体，尾实体，关系的意思
谢谢，非常期待您的回复！

**Comment by Mrlyk423** [comment]
你好，前两个是实体的mid，最后是relation，/是relation层级结构的分层。
