### ISSUE TITLE
MeanRank没有达到200+

### ISSUE THREAD

**Issue by ghost** [thunlp/KB2E#7]
您好，我跑了几次您transE实现的代码，试了许多参数，但是实验结果显示MeanRank都没有达到200多，最好的只有400+的情况。我们用的数据是 wordnet18的数据，下降1000轮，学习率试过[0.01, 0.001]，vector 维度试过[20, 100]，margin 试过[1, 2]。请问是参数或者程序还有要修改的地方吗？
谢谢，祝好~

**Comment by guotong1988** [comment]
大神，您实际跑了，可否简单讲下这个项目是在做一件什么事？多谢啊！

**Comment by Mrlyk423** [comment]
如论文所示，wordnet18的margin应该是4

**Comment by lylalala** [comment]
论文中似乎说训练transE只需要3分钟，这么短的时间可以吗？楼上都训练了多久啊？我用的项目的数据集，训练要好几个小时。求解。谢了
