### ISSUE TITLE
unable to generate "output/train_cluster.txt:

### ISSUE THREAD

**Issue by Osanchez** [thunlp/KB2E#72]
I am using bash run.sh 1 as parameter to generate train_cluster.txt file and am given the following input 

0
0 0 0

maxits=500, convits=50, dampfact=0.900000

Number of identified clusters: 8
Fitness (net similarity): 0.000000
  Similarities of data points to exemplars: 0.000000
  Preferences of selected exemplars: 0.000000
Number of iterations: 83

0
1
2
....
155
...

My question, what am I missing to generate this file? I am getting pre.txt and similarity.txt files which appear to have empty data.

pre.txt

0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
...

similarity.txt

1	2	0.000000
1	3	0.000000
1	4	0.000000
1	5	0.000000
1	6	0.000000
1	7	0.000000
1	8	0.000000
1	9	0.000000
1	10	0.000000
1	11	0.000000
1	12	0.000000
1	13	0.000000
1	14	0.000000
...

**Comment by Mrlyk423** [comment]
You need to first train TransE model, and got the embedding file "./TransE/entity2vec.txt2".
