### ISSUE TITLE
How to do the relation extraction with NYT+FreeBase

### ISSUE THREAD

**Issue by IdelCoder** [thunlp/KB2E#74]
I am really confused by the relation extraction in the paper **Modeling Relation Paths for Representation Learning of Knowledge Bases**.
First, I don't understand why I need to get the New York Times Corpus that you mentioned in readme. I think the NYT+Freebase is already constructed by Riedel. Did you mean that we need to do the alignment of NYT and Freebase on our own? 
Second, I want to know how FB40K is constructed. Does it generated from the Freebase whose dump size is nearly 300G? If it does, this will address my another question that how the id of an entity in FB40K (e.g., m.01063t) is mapped to the NYT real entity name.
It is possible that I misunderstood the relation extraction. I hope you can give me a complete guide.

**Comment by Mrlyk423** [comment]
1. New York Times Corpus is used to pre-train the word embeddings used in Sm2r.
2. Yes, it is generated from the whole FB. NYT10 dataset provides the entities' "uid" of each sentence, and the "uid" could transfer to "mid" in FB.

**Comment by Airuibadi** [comment]
> 1. New York Times Corpus is used to pre-train the word embeddings used in Sm2r.
> 2. Yes, it is generated from the whole FB. NYT10 dataset provides the entities' "uid" of each sentence, and the "uid" could transfer to "mid" in FB.

Thank you. But how can I transfer the 'uid' to 'mid', is there any code?
