### ISSUE TITLE
Train_TransR.cpp BUG

### ISSUE THREAD

**Issue by ghost** [thunlp/KB2E#8]
#236-#237：
 norm(entity_tmp[k]);
这里 k 值与实体数量有什么关系？当 train.txt 容量大于实体数量100倍时会引起段错误。

**Comment by guotong1988** [comment]
大神，您实际跑了，可否简单讲下这个项目是在做一件什么事？多谢啊！

**Comment by ghost** [comment]
三元组训练成向量的不同模型

**Comment by Mrlyk423** [comment]
这一句是个bug，已经去掉。

**Comment by guotong1988** [comment]
要跑多长时间，我看TransE写得`epoch = 1000`
