### ISSUE TITLE
The testing command

### ISSUE THREAD

**Issue by johnnychhsu** [thunlp/KB2E#80]
It loos like we should run
`./Test_TransE bern`

I would like to add it to readme

**Comment by summerstay** [comment]
Thanks, this helped

**Comment by FloatingMaple** [comment]
Thanks! 
Then i get 

`1345 14951
left:307.139 0.476207 187.745 0.682145
right:167.528 0.557177 91.4482 0.748692
`
could you please tell me what they means?

**Comment by johnnychhsu** [comment]
I think you can find the metric in the paper, there are some explanations.
