### ISSUE TITLE
Obtaining PTransE-specific dataset

### ISSUE THREAD

**Issue by AndRossi** [thunlp/KB2E#86]
I'm trying to run a PTransE training. 
Unfortunately, reading the README.md for PTransE, it seems that a specific version of the dataset is required, and it seems that it can only be downloaded from **pan.baidu.com**. 

I am not registered to pan.baidu, and the registration process seems quite complicated (unfortunately I can't read Chinese).

Is there another way to obtain it? 
Thank you for your kind support.

**Comment by rachzhang** [comment]
it was a quite huge text file... i split it into smaller ones to upload here. you need to merge them after downloading. 

btw, i am not sure where those "the top-500 entity pairs which are calculated by TransE" come from. This file contains 22M pairs (including self-loop)

[e1_e2.txt.part_aa.gz](https://github.com/thunlp/KB2E/files/3649161/e1_e2.txt.part_aa.gz)
[e1_e2.txt.part_ab.gz](https://github.com/thunlp/KB2E/files/3649162/e1_e2.txt.part_ab.gz)
[e1_e2.txt.part_ac.gz](https://github.com/thunlp/KB2E/files/3649164/e1_e2.txt.part_ac.gz)
[e1_e2.txt.part_ad.gz](https://github.com/thunlp/KB2E/files/3649168/e1_e2.txt.part_ad.gz)
[e1_e2.txt.part_al.gz](https://github.com/thunlp/KB2E/files/3649169/e1_e2.txt.part_al.gz)
[e1_e2.txt.part_ak.gz](https://github.com/thunlp/KB2E/files/3649170/e1_e2.txt.part_ak.gz)
[e1_e2.txt.part_aj.gz](https://github.com/thunlp/KB2E/files/3649171/e1_e2.txt.part_aj.gz)
[e1_e2.txt.part_ai.gz](https://github.com/thunlp/KB2E/files/3649172/e1_e2.txt.part_ai.gz)
[e1_e2.txt.part_ah.gz](https://github.com/thunlp/KB2E/files/3649173/e1_e2.txt.part_ah.gz)
[e1_e2.txt.part_ag.gz](https://github.com/thunlp/KB2E/files/3649174/e1_e2.txt.part_ag.gz)
[e1_e2.txt.part_af.gz](https://github.com/thunlp/KB2E/files/3649175/e1_e2.txt.part_af.gz)
[e1_e2.txt.part_ae.gz](https://github.com/thunlp/KB2E/files/3649176/e1_e2.txt.part_ae.gz)

**Comment by AndRossi** [comment]
Thank you so much! 
Woah, I didn't expect so many entries, this is really weird...

**Comment by AndRossi** [comment]
Since this issue is technically solved I'm going to close it. 
However @rachzhang I'm going to open another one to understand how exactly e1_e2.txt is done (I'd like to test PTransE on other datasets so I need to be able to generate it)
