### ISSUE TITLE
TransH中没有测试代码？

### ISSUE THREAD

**Issue by iunderstand** [thunlp/KB2E#9]
TransH中，只有训练的，没有测试代码？

**Comment by Mrlyk423** [comment]
由于不是我的个人实验，只提供了训练代码，需要可以向我发邮件。

**Comment by dajunxiao** [comment]
你好，可以给我发一份TransH测试代码吗？我的邮箱632373808@qq.com

**Comment by wyue0824** [comment]
您好，最近在参考您的代码，可以发一份TransH的测试代码吗？感谢您！我的邮箱：819035422@qq.com

**Comment by iamdawn** [comment]
你好，可以发一份TransH的测试代码吗？邮箱3249845108@qq.com，感谢您！

**Comment by tian1152010110** [comment]
您好，希望同求一份transH中的test文件，2282550468@qq.com ，非常感激！


------------------ 原始邮件 ------------------
发件人: "MartinHero"<notifications@github.com>;
发送时间: 2019年4月22日(星期一) 下午4:52
收件人: "thunlp/KB2E"<KB2E@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [thunlp/KB2E] TransH中没有测试代码？ (#9)




你好，可以发一份TransH的测试代码吗？邮箱3249845108@qq.com，感谢您！
